In [1]:
#Sudoku
board = [[0,0,0,0,8,4,0,0,3],
        [1,3,0,0,5,0,0,9,4],
        [9,0,5,0,1,3,0,7,0],
        [4,0,0,0,9,6,0,0,0],
        [0,0,3,7,0,0,0,0,1],
        [7,5,0,0,3,0,4,6,9],
        [5,0,4,0,7,8,0,2,0],
        [3,6,0,0,2,9,0,5,0],
        [0,2,0,0,0,0,3,0,7]]


def solve(bo):
    find = find_empty(bo)
    if not find:
        return True
    else:
        row, col = find

    for i in range(1,10):
        if valid(bo, i, (row, col)):
            bo[row][col] = i

            if solve(bo):
                return True

            bo[row][col] = 0

    return False


def valid(bo, num, pos):
    # Check row
    for i in range(len(bo[0])):
        if bo[pos[0]][i] == num and pos[1] != i:
            return False

    # Check column
    for i in range(len(bo)):
        if bo[i][pos[1]] == num and pos[0] != i:
            return False

    # Check box
    box_x = pos[1] // 3
    box_y = pos[0] // 3

    for i in range(box_y*3, box_y*3 + 3):
        for j in range(box_x * 3, box_x*3 + 3):
            if bo[i][j] == num and (i,j) != pos:
                return False

    return True


def find_empty(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j] == 0:
                return (i, j)  # row, col

    return None


solve(board)
print(board)

[[2, 7, 6, 9, 8, 4, 5, 1, 3], [1, 3, 8, 2, 5, 7, 6, 9, 4], [9, 4, 5, 6, 1, 3, 8, 7, 2], [4, 8, 2, 1, 9, 6, 7, 3, 5], [6, 9, 3, 7, 4, 5, 2, 8, 1], [7, 5, 1, 8, 3, 2, 4, 6, 9], [5, 1, 4, 3, 7, 8, 9, 2, 6], [3, 6, 7, 4, 2, 9, 1, 5, 8], [8, 2, 9, 5, 6, 1, 3, 4, 7]]


In [4]:
#Magic Square
import numpy as np
N  = int(input("Enter the size:"))

magic = np.zeros((N,N), dtype=int)
n = 1
i= 0
j = N//2

while n <= N**2:
    magic[i, j] = n
    n+=1
    x = (i-1) % N
    y = (j+1)% N
    if magic[x, y]:
        i +=1
    else:
        i, j = x, y
print("The Magic Square is:")
print(magic)

Enter the size:3
The Magic Square is:
[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [5]:
#Tic-Tac-Toe
def ConstBoard(board): #creating Board
    print("Current State Of Board : \n\n");
    for i in range (0,9):
        if((i>0) and (i%3)==0):
            print("\n");
        if(board[i]==0):
            print("- ",end=" ");
        if (board[i]==1):
            print("O ",end=" ");
        if(board[i]==-1):    
            print("X ",end=" ");
    print("\n\n");
def Player1Turn(board):               
    pos=input("Enter X's position from [1...9]: ");
    pos=int(pos);
    if(board[pos-1]!=0):
        print("Wrong Move!!!");
        exit(0) ;
    board[pos-1]=-1;
def Player2Turn(board):                
    pos=input("Enter O's position from [1...9]: ");
    pos=int(pos);
    if(board[pos-1]!=0):
        print("Wrong Move!!!");
        exit(0);
    board[pos-1]=1;
def minimax(board,player):            #MinMax function.
    x=analyzeboard(board);
    if(x!=0):
        return (x*player);
    pos=-1;
    value=-2;
    for i in range(0,9):
        if(board[i]==0):
            board[i]=player;
            score=-minimax(board,(player*-1));
            if(score>value):
                value=score;
                pos=i;
            board[i]=0;

    if(pos==-1):
        return 0;
    return value;  
def CompTurn(board):             #computer move
    pos=-1;
    value=-2;
    for i in range(0,9):
        if(board[i]==0):
            board[i]=1;
            score=-minimax(board, -1);
            board[i]=0;
            if(score>value):
                value=score;
                pos=i;
 
    board[pos]=1;

def analyzeboard(board):              #condition checking
    cb=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];

    for i in range(0,8):
        if(board[cb[i][0]] != 0 and
           board[cb[i][0]] == board[cb[i][1]] and
           board[cb[i][0]] == board[cb[i][2]]):
            return board[cb[i][2]];
    return 0;
#Main Function.
def main():
    choice=input("Enter 1 for single player, 2 for multiplayer: ");
    choice=int(choice);
    board=[0,0,0,0,0,0,0,0,0];
    if(choice==1):
        print("Computer : O Vs. You : X");
        player= input("Enter to play 1(st) or 2(nd) :");
        player = int(player);
        for i in range (0,9):
            if(analyzeboard(board)!=0):
                break;
            if((i+player)%2==0):
                CompTurn(board);
            else:
                ConstBoard(board);
                Player1Turn(board);
    else:
        for i in range (0,9):
            if(analyzeboard(board)!=0):
                break;
            if((i)%2==0):
                ConstBoard(board);
                User1Turn(board);
            else:
                ConstBoard(board);
                Player2Turn(board);
                 
    x=analyzeboard(board);
    if(x==0):
        ConstBoard(board);
        print("Draw!!!")
    if(x==-1):
        ConstBoard(board);
        print("X Wins!!! Y Loose !!!")
    if(x==1):
        ConstBoard(board);
        print("X Loose!!! O Wins !!!!")
       
#---------------#
main()
#---------------#

Enter 1 for single player, 2 for multiplayer: 1
Computer : O Vs. You : X
Enter to play 1(st) or 2(nd) :1
Current State Of Board : 


-  -  -  

-  -  -  

-  -  -  


Enter X's position from [1...9]: 5
Current State Of Board : 


O  -  -  

-  X  -  

-  -  -  


Enter X's position from [1...9]: 3
Current State Of Board : 


O  -  X  

-  X  -  

O  -  -  


Enter X's position from [1...9]: 2
Current State Of Board : 


O  X  X  

O  X  -  

O  -  -  


X Loose!!! O Wins !!!!


In [6]:
#N-Queens
import copy
import random

def take_input():
    while True:
        try:
            n = int(input('Input size of chessboard? n = '))
            if n <= 3:
                print("Enter a value greater than or equal to 4")
                continue
            return n
        except ValueError:
            print("Invalid value entered. Enter again")

def get_board(n):     #Returns an n by n board
    board = ["x"]*n
    for i in range(n):
        board[i] = ["x"]*n
    return board

def print_solution(solutions, n):      
    x = random.randint(0,1) 
    for row in solutions[x]:
        print(" ".join(row))

def solve(board, col, n):     #Using backtracking 
    if col >= n:
        return
    
    for i in range(n):
        if is_safe(board, i, col, n):
            board[i][col] = "Q"
            if col == n-1:
                add_solution(board)
                board[i][col] = "x"
                return
            solve(board, col+1, n) 
            #backtracking
            board[i][col] = "x"
            
def is_safe(board, row, col, n):     #Check if it's safe to place a queen at board[x][y]
                                     #check row on left side
    for j in range(col):
        if board[row][j] == "Q":
            return False
    
    i, j = row, col
    while i >= 0 and j >= 0:
        if board[i][j] == "Q":
            return False
        i=i-1
        j=j-1
    
    x, y = row,col
    while x < n and y >= 0:
        if board[x][y] == "Q":
            return False
        x=x+1
        y=y-1
    
    return True

def add_solution(board):
    global solutions
    saved_board = copy.deepcopy(board)
    solutions.append(saved_board)

n = take_input()
board = get_board(n)
solutions = []

solve(board, 0, n)

print()

print("One of the solutions is: \n")
print_solution(solutions, n)

Input size of chessboard? n = 8

One of the solutions is: 

Q x x x x x x x
x x x x x x Q x
x x x x Q x x x
x x x x x x x Q
x Q x x x x x x
x x x Q x x x x
x x x x x Q x x
x x Q x x x x x


In [7]:
#Knight Tour
chess_board = [[1,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0]]

def print_board(): #function to print the chess board
    for i in range(8):
        for j in range(8):
            print(chess_board[i][j], end=" ")
        print("\n")
def get_possibilities(x, y):
    pos_x = (2, 1, 2, 1, -2, -1, -2, -1)
    pos_y = (1, 2, -1, -2, 1, 2, -1, -2)
    possibilities = []
    for i in range(8):
        if x+pos_x[i] >= 0 and x+pos_x[i] <= 7 and y+pos_y[i] >= 0 and y+pos_y[i] <= 7 and chess_board[x+pos_x[i]][y+pos_y[i]] == 0:
            possibilities.append([x+pos_x[i], y+pos_y[i]])
    return possibilities

def solve():
    counter = 2
    x = 0
    y = 0
    for i in range(63): 
        pos = get_possibilities(x, y) 
        minimum = pos[0]
        for p in pos:
            if len(get_possibilities(p[0], p[1])) <= len(get_possibilities(minimum[0], minimum[1])):
                minimum = p
        x = minimum[0]
        y = minimum[1]
        chess_board[x][y] = counter
        counter += 1

solve()    
print_board()

1 16 31 54 3 18 21 58 

30 43 2 17 50 57 4 19 

15 32 53 46 55 20 59 22 

42 29 44 49 60 51 56 5 

33 14 47 52 45 64 23 62 

28 41 34 37 48 61 6 9 

13 36 39 26 11 8 63 24 

40 27 12 35 38 25 10 7 



In [8]:
#8-Puzzle
from copy import deepcopy
import numpy as np
import time

# takes the input of current states and evaluvates the best path to goal state
def bestsolution(state):
    bestsol = np.array([], int).reshape(-1, 9)
    count = len(state) - 1
    while count != -1:
        bestsol = np.insert(bestsol, 0, state[count]['puzzle'], 0)
        count = (state[count]['parent'])
    return bestsol.reshape(-1, 3, 3)

# calculate Manhattan distance cost between each digit of puzzle(start state) and the goal state
def manhattan(puzzle, goal):
    a = abs(puzzle // 3 - goal // 3)
    b = abs(puzzle % 3 - goal % 3)
    mhcost = a + b
    return sum(mhcost[1:])

#3[on_true] if [expression] else [on_false] 

# will indentify the coordinates of each of goal or initial state values
def coordinates(puzzle):
    pos = np.array(range(9))
    for p, q in enumerate(puzzle):
        pos[q] = p
    return pos

# start of 8 puzzle evaluvation, using Manhattan heuristics 
def evaluvate(puzzle, goal):
    steps = np.array([('up', [0, 1, 2], -3),('down', [6, 7, 8],  3),('left', [0, 3, 6], -1),('right', [2, 5, 8],  1)],
                dtype =  [('move',  str, 1),('position', list),('head', int)])

    dtstate = [('puzzle',  list),('parent', int),('gn',  int),('hn',  int)]
     # initializing the parent, gn and hn, where hn is manhattan distance function call 
    costg = coordinates(goal)
    parent = -1
    gn = 0
    hn = manhattan(coordinates(puzzle), costg)
    state = np.array([(puzzle, parent, gn, hn)], dtstate)

# We make use of priority queues with position as keys and fn as value.
    dtpriority = [('position', int),('fn', int)]
    priority = np.array( [(0, hn)], dtpriority)
    while 1:
        priority = np.sort(priority, kind='mergesort', order=['fn', 'position'])     
        position, fn = priority[0]                                                 
        priority = np.delete(priority, 0, 0)  
        # sort priority queue using merge sort,the first element is picked for exploring remove from queue what we are exploring                   
        puzzle, parent, gn, hn = state[position]
        puzzle = np.array(puzzle)
        # Identify the blank square in input 
        blank = int(np.where(puzzle == 0)[0])       
        gn = gn + 1                              
        c = 1
        start_time = time.time()
        for s in steps:
            c = c + 1
            if blank not in s['position']:
                # generate new state as copy of current
                openstates = deepcopy(puzzle)                   
                openstates[blank], openstates[blank + s['head']] = openstates[blank + s['head']], openstates[blank]             
                # The all function is called, if the node has been previously explored or not
                if ~(np.all(list(state['puzzle']) == openstates, 1)).any():    
                    end_time = time.time()
                    if (( end_time - start_time ) > 2):
                        print(" The 8 puzzle is unsolvable ! \n")
                        exit 
                    # calls the manhattan function to calcuate the cost 
                    hn = manhattan(coordinates(openstates), costg)    
                     # generate and add new state in the list                    
                    q = np.array([(openstates, position, gn, hn)], dtstate)         
                    state = np.append(state, q, 0)
                    # f(n) is the sum of cost to reach node and the cost to rech fromt he node to the goal state
                    fn = gn + hn                                        
            
                    q = np.array([(len(state) - 1, fn)], dtpriority)    
                    priority = np.append(priority, q, 0)
                      # Checking if the node in openstates are matching the goal state.  
                    if np.array_equal(openstates, goal):                              
                        print(' The 8 puzzle is solvable ! \n')
                        return state, len(priority)
        
                        
    return state, len(priority)
 
puzzle = []
print(" Input vals from 0-8 for start state ")
for i in range(0,9):
    x = int(input("enter vals :"))
    puzzle.append(x)
       
goal = []
print(" Input vals from 0-8 for goal state ")
for i in range(0,9):
    x = int(input("Enter vals :"))
    goal.append(x)
    
print("Using Manhatten Distance:")
state, visited = evaluvate(puzzle, goal) 
bestpath = bestsolution(state)
print(str(bestpath).replace('[', ' ').replace(']', ''))
totalmoves = len(bestpath) - 1
print('Steps to reach goal:',totalmoves)

 Input vals from 0-8 for start state 
enter vals :1
enter vals :2
enter vals :3
enter vals :0
enter vals :6
enter vals :5
enter vals :8
enter vals :7
enter vals :4
 Input vals from 0-8 for goal state 
Enter vals :1
Enter vals :2
Enter vals :3
Enter vals :4
Enter vals :5
Enter vals :6
Enter vals :7
Enter vals :8
Enter vals :0
Using Manhatten Distance:
 The 8 puzzle is solvable ! 

   1 2 3
   0 6 5
   8 7 4

   1 2 3
   8 6 5
   0 7 4

   1 2 3
   8 6 5
   7 0 4

   1 2 3
   8 0 5
   7 6 4

   1 2 3
   8 5 0
   7 6 4

   1 2 3
   8 5 4
   7 6 0

   1 2 3
   8 5 4
   7 0 6

   1 2 3
   8 0 4
   7 5 6

   1 2 3
   0 8 4
   7 5 6

   1 2 3
   7 8 4
   0 5 6

   1 2 3
   7 8 4
   5 0 6

   1 2 3
   7 0 4
   5 8 6

   1 2 3
   7 4 0
   5 8 6

   1 2 3
   7 4 6
   5 8 0

   1 2 3
   7 4 6
   5 0 8

   1 2 3
   7 4 6
   0 5 8

   1 2 3
   0 4 6
   7 5 8

   1 2 3
   4 0 6
   7 5 8

   1 2 3
   4 5 6
   7 0 8

   1 2 3
   4 5 6
   7 8 0
Steps to reach goal: 19
